import = [
  "~/.config/alacritty/moonfly.toml",
]

[font]
size = 14.0

[font.normal]
family = "FiraCode Nerd Font"
style = "Retina"

[window]
decorations = "none"
opacity = 0.9

[env]
TERM = "xterm-256color"

[scrolling]
history = 10000
multiplier = 3
