[font]
size = 14.0

[font.normal]
family = "FiraCode Nerd Font"
style = "Retina"

[window]
decorations = "none"
opacity = 0.9

[scrolling]
history = 10000
multiplier = 3

# https://github.com/bluz71/vim-moonfly-colors
[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
background = "#080808"
foreground = "#bdbdbd"
bright_foreground = "#eeeeee"

[colors.cursor]
cursor = "#8e8e8e"
text = "#080808"

[colors.selection]
background = "#b2ceee"
text = "#080808"

[colors.normal]
black = "#323437"
red = "#ff5454"
green = "#8cc85f"
yellow = "#e3c78a"
blue = "#80a0ff"
magenta = "#cf87e8"
cyan = "#79dac8"
white = "#c6c6c6"

[colors.bright]
black = "#949494"
red = "#ff5189"
green = "#36c692"
yellow = "#c2c292"
blue = "#74b2ff"
magenta = "#ae81ff"
cyan = "#85dc85"
white = "#e4e4e4"
